### ISSUE TITLE
Glow does not work ... 

### ISSUE THREAD

**Issue by bugaoleg** [spirthack/CSGOSimple#53]
After may 2019 update, glow does not work ... I have update all index, all works fine except glow. Glow on players work only if chams and ingnore Z is working. If you just enable glow on players, it makes glowing only weapons they have in hands ...

**Comment by anarh1st47** [comment]
fixed in https://github.com/spirthack/CSGOSimple/commit/083fde401e385f0d923686f4909215944af74b75, please try it and feedback here

**Comment by bugaoleg** [comment]
> fixed in [083fde4](https://github.com/spirthack/CSGOSimple/commit/083fde401e385f0d923686f4909215944af74b75), please try it and feedback here

Yeah ... that fixed the problem with glow ... just one problem remain. When I turn on glow for chickens, sometimes players chickens weapons make full white color, even if chams is turned on
